var utData = {
  "fundList": [
    {
      "pid": "UT002",
      "fundHouse": "House Name 2",
      "investCategory": "category 2",
      "region": "Hong Kong",
      "riskProfile": "risk2",
      "fundName": "House Name 2 : category 2 - HKD",
      "currency": "HKD",
      "threeMth": "+12.75",
      "sixMth": "+3.02",
      "oneYr": "-2.01",
      "threeYr": "+18.99",
      "threeYrsd": "+10.24",
      "percentage": "3.37%",
      "investMedium": "mediun 1",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT003",
      "fundHouse": "House Name 2",
      "investCategory": "category 1",
      "region": "Hong Kong",
      "riskProfile": "risk3",
      "fundName": "[FOCUS FUND] House Name 2 : category 1 - HKD",
      "currency": "HKD",
      "threeMth": "+1.05",
      "sixMth": "+30.00",
      "oneYr": "-8.01",
      "threeYr": "+8.09",
      "threeYrsd": "+20.04",
      "percentage": "4.05%",
      "investMedium": "mediun 2",
      "isFocusFund": true,
      "focusFund": "FOCUS FUND",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT004",
      "fundHouse": "House Name 3",
      "investCategory": "category 2",
      "region": "Taiwan",
      "riskProfile": "risk4",
      "fundName": "House Name 3 : category 2 - TWD",
      "currency": "TWD",
      "threeMth": "+22.05",
      "sixMth": "+5.60",
      "oneYr": "-2.91",
      "threeYr": "+77.09",
      "threeYrsd": "+32.14",
      "percentage": "8.11%",
      "investMedium": "mediun 3",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT005",
      "fundHouse": "House Name 3",
      "investCategory": "category 2",
      "region": "Taiwan",
      "riskProfile": "risk4",
      "fundName": "House Name 3 : category 2 - TWD",
      "currency": "TWD",
      "threeMth": "+20.05",
      "sixMth": "+50.60",
      "oneYr": "-20.01",
      "threeYr": "+70.00",
      "threeYrsd": "+2.10",
      "percentage": "2.14%",
      "investMedium": "mediun 4",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT006",
      "fundHouse": "House Name 1",
      "investCategory": "category 1",
      "region": "Singapore",
      "riskProfile": "risk4",
      "fundName": "House Name 1 : category 2 - SGD",
      "currency": "SGD",
      "threeMth": "+3.05",
      "sixMth": "+4.60",
      "oneYr": "-1.31",
      "threeYr": "+3.00",
      "threeYrsd": "+6.90",
      "percentage": "3.14%",
      "investMedium": "mediun 2",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT007",
      "fundHouse": "House Name 2",
      "investCategory": "category 2",
      "region": "Singapore",
      "riskProfile": "risk4",
      "fundName": "House Name 2 : category 2 - SGD",
      "currency": "SGD",
      "threeMth": "+6.05",
      "sixMth": "+32.00",
      "oneYr": "-4.31",
      "threeYr": "+43.90",
      "threeYrsd": "+21.90",
      "percentage": "4.54%",
      "investMedium": "mediun 2",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT008",
      "fundHouse": "House Name 1",
      "investCategory": "category 1",
      "region": "Singapore",
      "riskProfile": "risk1",
      "fundName": "House Name 1 : category 1 - SGD",
      "currency": "SGD",
      "threeMth": "+21.70",
      "sixMth": "+12.02",
      "oneYr": "-1.01",
      "threeYr": "+7.09",
      "threeYrsd": "+2.51",
      "percentage": "23.30%",
      "investMedium": "mediun 1",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT009",
      "fundHouse": "House Name 2",
      "investCategory": "category 2",
      "region": "Hong Kong",
      "riskProfile": "risk2",
      "fundName": "House Name 2 : category 2 - HKD",
      "currency": "HKD",
      "threeMth": "+12.75",
      "sixMth": "+3.02",
      "oneYr": "-2.01",
      "threeYr": "+18.99",
      "threeYrsd": "+10.24",
      "percentage": "13.31%",
      "investMedium": "mediun 1",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT010",
      "fundHouse": "House Name 2",
      "investCategory": "category 1",
      "region": "Hong Kong",
      "riskProfile": "risk3",
      "fundName": "House Name 2 : category 1 - HKD",
      "currency": "HKD",
      "threeMth": "+1.05",
      "sixMth": "+30.00",
      "oneYr": "-8.01",
      "threeYr": "+8.09",
      "threeYrsd": "+20.04",
      "percentage": "10.30%",
      "investMedium": "mediun 2",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT011",
      "fundHouse": "House Name 3",
      "investCategory": "category 2",
      "region": "Taiwan",
      "riskProfile": "risk4",
      "fundName": "House Name 3 : category 2 - TWD",
      "currency": "TWD",
      "threeMth": "+21.35",
      "sixMth": "+5.60",
      "oneYr": "-2.91",
      "threeYr": "+77.09",
      "threeYrsd": "+32.14",
      "percentage": "17.20%",
      "investMedium": "mediun 3",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT012",
      "fundHouse": "House Name 3",
      "investCategory": "category 2",
      "region": "Taiwan",
      "riskProfile": "risk4",
      "fundName": "[FOCUS FUND] House Name 3 : category 2 - TWD",
      "currency": "TWD",
      "threeMth": "+20.05",
      "sixMth": "+50.60",
      "oneYr": "-20.01",
      "threeYr": "+70.00",
      "threeYrsd": "+2.10",
      "percentage": "8.23%",
      "investMedium": "mediun 4",
      "isFocusFund": true,
      "focusFund": "FOCUS FUND",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT013",
      "fundHouse": "House Name 1",
      "investCategory": "category 1",
      "region": "Singapore",
      "riskProfile": "risk4",
      "fundName": "House Name 1 : category 2 - SGD",
      "currency": "SGD",
      "threeMth": "+3.05",
      "sixMth": "+4.60",
      "oneYr": "-1.31",
      "threeYr": "+3.00",
      "threeYrsd": "+6.90",
      "percentage": "4.14%",
      "investMedium": "mediun 2",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT014",
      "fundHouse": "House Name 2",
      "investCategory": "category 2",
      "region": "Singapore",
      "riskProfile": "risk4",
      "fundName": "House Name 2 : category 2 - SGD",
      "currency": "SGD",
      "threeMth": "+6.05",
      "sixMth": "+32.00",
      "oneYr": "-4.31",
      "threeYr": "+43.90",
      "threeYrsd": "+21.90",
      "percentage": "5.04%",
      "investMedium": "mediun 2",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT015",
      "fundHouse": "House Name 1",
      "investCategory": "category 1",
      "region": "Singapore",
      "riskProfile": "risk1",
      "fundName": "[FocusFund] House Name 1 : category 1 - SGD",
      "currency": "SGD",
      "threeMth": "+20.05",
      "sixMth": "+11.02",
      "oneYr": "-1.01",
      "threeYr": "+6.99",
      "threeYrsd": "+3.14",
      "percentage": "22.36%",
      "investMedium": "mediun 1",
      "isFocusFund": true,
      "focusFund": "FOCUS FUND",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT016",
      "fundHouse": "House Name 2",
      "investCategory": "category 2",
      "region": "Hong Kong",
      "riskProfile": "risk2",
      "fundName": "House Name 2 : category 2 - HKD",
      "currency": "HKD",
      "threeMth": "+12.75",
      "sixMth": "+3.02",
      "oneYr": "-2.01",
      "threeYr": "+18.99",
      "threeYrsd": "+10.24",
      "percentage": "12.17%",
      "investMedium": "mediun 1",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT017",
      "fundHouse": "House Name 2",
      "investCategory": "category 1",
      "region": "Hong Kong",
      "riskProfile": "risk3",
      "fundName": "House Name 2 : category 1 - HKD",
      "currency": "HKD",
      "threeMth": "+1.05",
      "sixMth": "+30.00",
      "oneYr": "-8.01",
      "threeYr": "+8.09",
      "threeYrsd": "+20.04",
      "percentage": "9.00%",
      "investMedium": "mediun 2",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT018",
      "fundHouse": "House Name 3",
      "investCategory": "category 2",
      "region": "Taiwan",
      "riskProfile": "risk4",
      "fundName": "House Name 3 : category 2 - TWD",
      "currency": "TWD",
      "threeMth": "+20.25",
      "sixMth": "+5.60",
      "oneYr": "-2.91",
      "threeYr": "+77.09",
      "threeYrsd": "+32.14",
      "percentage": "16.12%",
      "investMedium": "mediun 3",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT019",
      "fundHouse": "House Name 3",
      "investCategory": "category 2",
      "region": "Taiwan",
      "riskProfile": "risk4",
      "fundName": "[FOCUS FUND] House Name 3 : category 2 - TWD",
      "currency": "TWD",
      "threeMth": "+20.05",
      "sixMth": "+50.60",
      "oneYr": "-20.01",
      "threeYr": "+70.00",
      "threeYrsd": "+2.10",
      "percentage": "7.11%",
      "investMedium": "mediun 4",
      "isFocusFund": true,
      "focusFund": "FOCUS FUND",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT020",
      "fundHouse": "House Name 1",
      "investCategory": "category 1",
      "region": "Singapore",
      "riskProfile": "risk4",
      "fundName": "House Name 1 : category 2 - SGD",
      "currency": "SGD",
      "threeMth": "+3.05",
      "sixMth": "+4.60",
      "oneYr": "-1.31",
      "threeYr": "+3.00",
      "threeYrsd": "+6.90",
      "percentage": "5.14%",
      "investMedium": "mediun 2",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT021",
      "fundHouse": "House Name 2",
      "investCategory": "category 2",
      "region": "Singapore",
      "riskProfile": "risk4",
      "fundName": "House Name 2 : category 2 - SGD",
      "currency": "SGD",
      "threeMth": "+6.05",
      "sixMth": "+32.00",
      "oneYr": "-4.31",
      "threeYr": "+43.90",
      "threeYrsd": "+21.90",
      "percentage": "6.50%",
      "investMedium": "mediun 2",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT022",
      "fundHouse": "House Name 1",
      "investCategory": "category 1",
      "region": "Singapore",
      "riskProfile": "risk1",
      "fundName": "House Name 1 : category 1 - SGD",
      "currency": "SGD",
      "threeMth": "+19.15",
      "sixMth": "+10.02",
      "oneYr": "-1.01",
      "threeYr": "+5.90",
      "threeYrsd": "+4.23",
      "percentage": "22.35%",
      "investMedium": "mediun 1",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT023",
      "fundHouse": "House Name 2",
      "investCategory": "category 2",
      "region": "Hong Kong",
      "riskProfile": "risk2",
      "fundName": "House Name 2 : category 2 - HKD",
      "currency": "HKD",
      "threeMth": "+12.75",
      "sixMth": "+3.02",
      "oneYr": "-2.01",
      "threeYr": "+18.99",
      "threeYrsd": "+10.24",
      "percentage": "11.07%",
      "investMedium": "mediun 1",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT024",
      "fundHouse": "House Name 2",
      "investCategory": "category 1",
      "region": "Hong Kong",
      "riskProfile": "risk3",
      "fundName": "[FOCUS FUND] House Name 2 : category 1 - HKD",
      "currency": "HKD",
      "threeMth": "+1.05",
      "sixMth": "+30.00",
      "oneYr": "-8.01",
      "threeYr": "+8.09",
      "threeYrsd": "+20.04",
      "percentage": "9.10%",
      "investMedium": "mediun 2",
      "isFocusFund": true,
      "focusFund": "FOCUS FUND",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT025",
      "fundHouse": "House Name 3",
      "investCategory": "category 2",
      "region": "Taiwan",
      "riskProfile": "risk4",
      "fundName": "House Name 3 : category 2 - TWD",
      "currency": "TWD",
      "threeMth": "+19.15",
      "sixMth": "+5.60",
      "oneYr": "-2.91",
      "threeYr": "+77.09",
      "threeYrsd": "+32.14",
      "percentage": "15.11%",
      "investMedium": "mediun 3",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT026",
      "fundHouse": "House Name 3",
      "investCategory": "category 2",
      "region": "Taiwan",
      "riskProfile": "risk4",
      "fundName": "[FOCUS FUND] House Name 3 : category 2 - TWD",
      "currency": "TWD",
      "threeMth": "+20.05",
      "sixMth": "+50.60",
      "oneYr": "-20.01",
      "threeYr": "+70.00",
      "threeYrsd": "+2.10",
      "percentage": "7.24%",
      "investMedium": "mediun 4",
      "isFocusFund": true,
      "focusFund": "FOCUS FUND",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT027",
      "fundHouse": "House Name 1",
      "investCategory": "category 1",
      "region": "Singapore",
      "riskProfile": "risk4",
      "fundName": "House Name 1 : category 2 - SGD",
      "currency": "SGD",
      "threeMth": "+3.05",
      "sixMth": "+4.60",
      "oneYr": "-1.31",
      "threeYr": "+3.00",
      "threeYrsd": "+6.90",
      "percentage": "6.14%",
      "investMedium": "mediun 2",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT028",
      "fundHouse": "House Name 2",
      "investCategory": "category 2",
      "region": "Singapore",
      "riskProfile": "risk4",
      "fundName": "House Name 2 : category 2 - SGD",
      "currency": "SGD",
      "threeMth": "+6.05",
      "sixMth": "+32.00",
      "oneYr": "-4.31",
      "threeYr": "+43.90",
      "threeYrsd": "+21.90",
      "percentage": "7.54%",
      "investMedium": "mediun 2",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT029",
      "fundHouse": "House Name 1",
      "investCategory": "category 1",
      "region": "Singapore",
      "riskProfile": "risk1",
      "fundName": "House Name 1 : category 1 - SGD",
      "currency": "SGD",
      "threeMth": "+18.72",
      "sixMth": "+9.02",
      "oneYr": "-1.01",
      "threeYr": "+4.09",
      "threeYrsd": "+4.13",
      "percentage": "21.35%",
      "investMedium": "mediun 1",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT030",
      "fundHouse": "House Name 2",
      "investCategory": "category 2",
      "region": "Hong Kong",
      "riskProfile": "risk2",
      "fundName": "House Name 2 : category 2 - HKD",
      "currency": "HKD",
      "threeMth": "+12.75",
      "sixMth": "+3.02",
      "oneYr": "-2.01",
      "threeYr": "+18.99",
      "threeYrsd": "+10.24",
      "percentage": "10.30%",
      "investMedium": "mediun 1",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT031",
      "fundHouse": "House Name 2",
      "investCategory": "category 1",
      "region": "Hong Kong",
      "riskProfile": "risk3",
      "fundName": "[FOCUS FUND] House Name 2 : category 1 - HKD",
      "currency": "HKD",
      "threeMth": "+1.05",
      "sixMth": "+30.00",
      "oneYr": "-8.01",
      "threeYr": "+8.09",
      "threeYrsd": "+20.04",
      "percentage": "8.21%",
      "investMedium": "mediun 2",
      "isFocusFund": true,
      "focusFund": "FOCUS FUND",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT032",
      "fundHouse": "House Name 3",
      "investCategory": "category 2",
      "region": "Taiwan",
      "riskProfile": "risk4",
      "fundName": "House Name 3 : category 2 - TWD",
      "currency": "TWD",
      "threeMth": "+18.54",
      "sixMth": "+5.60",
      "oneYr": "-2.91",
      "threeYr": "+77.09",
      "threeYrsd": "+32.14",
      "percentage": "14.10%",
      "investMedium": "mediun 3",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT033",
      "fundHouse": "House Name 3",
      "investCategory": "category 2",
      "region": "Taiwan",
      "riskProfile": "risk4",
      "fundName": "[FOCUS FUND] House Name 3 : category 2 - TWD",
      "currency": "TWD",
      "threeMth": "+20.05",
      "sixMth": "+50.60",
      "oneYr": "-20.01",
      "threeYr": "+70.00",
      "threeYrsd": "+2.10",
      "percentage": "6.01%",
      "investMedium": "mediun 4",
      "isFocusFund": true,
      "focusFund": "FOCUS FUND",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT034",
      "fundHouse": "House Name 1",
      "investCategory": "category 1",
      "region": "Singapore",
      "riskProfile": "risk4",
      "fundName": "House Name 1 : category 2 - SGD",
      "currency": "SGD",
      "threeMth": "+3.05",
      "sixMth": "+4.60",
      "oneYr": "-1.31",
      "threeYr": "+3.00",
      "threeYrsd": "+6.90",
      "percentage": "7.14%",
      "investMedium": "mediun 2",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT035",
      "fundHouse": "House Name 2",
      "investCategory": "category 2",
      "region": "Singapore",
      "riskProfile": "risk4",
      "fundName": "House Name 2 : category 2 - SGD",
      "currency": "SGD",
      "threeMth": "+6.05",
      "sixMth": "+32.00",
      "oneYr": "-4.31",
      "threeYr": "+43.90",
      "threeYrsd": "+21.90",
      "percentage": "8.24%",
      "investMedium": "mediun 2",
      "isFocusFund": true,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT036",
      "fundHouse": "House Name 2",
      "investCategory": "category 2",
      "region": "Hong Kong",
      "riskProfile": "risk2",
      "fundName": "House Name 2 : category 2 - HKD",
      "currency": "HKD",
      "threeMth": "+12.75",
      "sixMth": "+3.02",
      "oneYr": "-2.01",
      "threeYr": "+18.99",
      "threeYrsd": "+10.24",
      "percentage": "9.21%",
      "investMedium": "mediun 1",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT037",
      "fundHouse": "House Name 2",
      "investCategory": "category 1",
      "region": "Hong Kong",
      "riskProfile": "risk3",
      "fundName": "[FOCUS FUND] House Name 2 : category 1 - HKD",
      "currency": "HKD",
      "threeMth": "+1.05",
      "sixMth": "+30.00",
      "oneYr": "-8.01",
      "threeYr": "+8.09",
      "threeYrsd": "+20.04",
      "percentage": "8.26%",
      "investMedium": "mediun 2",
      "isFocusFund": true,
      "focusFund": "FOCUS FUND",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT038",
      "fundHouse": "House Name 3",
      "investCategory": "category 2",
      "region": "Taiwan",
      "riskProfile": "risk4",
      "fundName": "House Name 3 : category 2 - TWD",
      "currency": "TWD",
      "threeMth": "+17.20",
      "sixMth": "+5.60",
      "oneYr": "-2.91",
      "threeYr": "+77.09",
      "threeYrsd": "+32.14",
      "percentage": "13.12%",
      "investMedium": "mediun 3",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT039",
      "fundHouse": "House Name 3",
      "investCategory": "category 2",
      "region": "Taiwan",
      "riskProfile": "risk4",
      "fundName": "[FOCUS FUND] House Name 3 : category 2 - TWD",
      "currency": "TWD",
      "threeMth": "+20.05",
      "sixMth": "+50.60",
      "oneYr": "-20.01",
      "threeYr": "+70.00",
      "threeYrsd": "+2.10",
      "percentage": "6.21%",
      "investMedium": "mediun 4",
      "isFocusFund": true,
      "focusFund": "FOCUS FUND",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT040",
      "fundHouse": "House Name 1",
      "investCategory": "category 1",
      "region": "Singapore",
      "riskProfile": "risk4",
      "fundName": "House Name 1 : category 2 - SGD",
      "currency": "SGD",
      "threeMth": "+3.05",
      "sixMth": "+4.60",
      "oneYr": "-1.31",
      "threeYr": "+3.00",
      "threeYrsd": "+6.90",
      "percentage": "8.14%",
      "investMedium": "mediun 2",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT041",
      "fundHouse": "House Name 2",
      "investCategory": "category 2",
      "region": "Singapore",
      "riskProfile": "risk4",
      "fundName": "House Name 2 : category 2 - SGD",
      "currency": "SGD",
      "threeMth": "+6.05",
      "sixMth": "+32.00",
      "oneYr": "-4.31",
      "threeYr": "+43.90",
      "threeYrsd": "+21.90",
      "percentage": "9.04%",
      "investMedium": "mediun 2",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT042",
      "fundHouse": "House Name 1",
      "investCategory": "category 1",
      "region": "Singapore",
      "riskProfile": "risk1",
      "fundName": "House Name 1 : category 1 - SGD",
      "currency": "SGD",
      "threeMth": "+17.05",
      "sixMth": "+8.02",
      "oneYr": "-1.01",
      "threeYr": "+3.99",
      "threeYrsd": "+5.26",
      "percentage": "20.33%",
      "investMedium": "mediun 1",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT043",
      "fundHouse": "House Name 2",
      "investCategory": "category 2",
      "region": "Hong Kong",
      "riskProfile": "risk2",
      "fundName": "House Name 2 : category 2 - HKD",
      "currency": "HKD",
      "threeMth": "+12.75",
      "sixMth": "+3.02",
      "oneYr": "-2.01",
      "threeYr": "+18.99",
      "threeYrsd": "+10.24",
      "percentage": "8.07%",
      "investMedium": "mediun 1",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT044",
      "fundHouse": "House Name 2",
      "investCategory": "category 1",
      "region": "Hong Kong",
      "riskProfile": "risk3",
      "fundName": "[FOCUS FUND] House Name 2 : category 1 - HKD",
      "currency": "HKD",
      "threeMth": "+1.05",
      "sixMth": "+30.00",
      "oneYr": "-8.01",
      "threeYr": "+8.09",
      "threeYrsd": "+20.04",
      "percentage": "7.30%",
      "investMedium": "mediun 2",
      "isFocusFund": true,
      "focusFund": "FOCUS FUND",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT045",
      "fundHouse": "House Name 3",
      "investCategory": "category 2",
      "region": "Taiwan",
      "riskProfile": "risk4",
      "fundName": "House Name 3 : category 2 - TWD",
      "currency": "TWD",
      "threeMth": "16.05",
      "sixMth": "+5.60",
      "oneYr": "-2.91",
      "threeYr": "+77.09",
      "threeYrsd": "+32.14",
      "percentage": "12.00%",
      "investMedium": "mediun 3",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT046",
      "fundHouse": "House Name 3",
      "investCategory": "category 2",
      "region": "Taiwan",
      "riskProfile": "risk4",
      "fundName": "[FOCUS FUND] House Name 3 : category 2 - TWD",
      "currency": "TWD",
      "threeMth": "+20.05",
      "sixMth": "+50.60",
      "oneYr": "-20.01",
      "threeYr": "+70.00",
      "threeYrsd": "+2.10",
      "percentage": "5.29%",
      "investMedium": "mediun 4",
      "isFocusFund": true,
      "focusFund": "FOCUS FUND",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT047",
      "fundHouse": "House Name 1",
      "investCategory": "category 1",
      "region": "Singapore",
      "riskProfile": "risk4",
      "fundName": "House Name 1 : category 2 - SGD",
      "currency": "SGD",
      "threeMth": "+3.05",
      "sixMth": "+4.60",
      "oneYr": "-1.31",
      "threeYr": "+3.00",
      "threeYrsd": "+6.90",
      "percentage": "9.14%",
      "investMedium": "mediun 2",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT048",
      "fundHouse": "House Name 2",
      "investCategory": "category 2",
      "region": "Singapore",
      "riskProfile": "risk4",
      "fundName": "House Name 2 : category 2 - SGD",
      "currency": "SGD",
      "threeMth": "+6.05",
      "sixMth": "+32.00",
      "oneYr": "-4.31",
      "threeYr": "+43.90",
      "threeYrsd": "+21.90",
      "percentage": "10.14%",
      "investMedium": "mediun 2",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT049",
      "fundHouse": "House Name 1",
      "investCategory": "category 1",
      "region": "Singapore",
      "riskProfile": "risk1",
      "fundName": "[FocusFund] House Name 1 : category 1 - SGD",
      "currency": "SGD",
      "threeMth": "+16.05",
      "sixMth": "+7.02",
      "oneYr": "-1.01",
      "threeYr": "+2.99",
      "threeYrsd": "+6.24",
      "percentage": "20.07%",
      "investMedium": "mediun 1",
      "isFocusFund": true,
      "focusFund": "FOCUS FUND",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT050",
      "fundHouse": "House Name 2",
      "investCategory": "category 2",
      "region": "Hong Kong",
      "riskProfile": "risk2",
      "fundName": "House Name 2 : category 2 - HKD",
      "currency": "HKD",
      "threeMth": "+12.75",
      "sixMth": "+3.02",
      "oneYr": "-2.01",
      "threeYr": "+18.99",
      "threeYrsd": "+10.24",
      "percentage": "7.00%",
      "investMedium": "mediun 1",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT051",
      "fundHouse": "House Name 2",
      "investCategory": "category 1",
      "region": "Hong Kong",
      "riskProfile": "risk3",
      "fundName": "[FOCUS FUND] House Name 2 : category 1 - HKD",
      "currency": "HKD",
      "threeMth": "+1.05",
      "sixMth": "+30.00",
      "oneYr": "-8.01",
      "threeYr": "+8.09",
      "threeYrsd": "+20.04",
      "percentage": "7.01%",
      "investMedium": "mediun 2",
      "isFocusFund": true,
      "focusFund": "FOCUS FUND",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT052",
      "fundHouse": "House Name 3",
      "investCategory": "category 2",
      "region": "Taiwan",
      "riskProfile": "risk4",
      "fundName": "House Name 3 : category 2 - TWD",
      "currency": "TWD",
      "threeMth": "+15.32",
      "sixMth": "+5.60",
      "oneYr": "-2.91",
      "threeYr": "+77.09",
      "threeYrsd": "+32.14",
      "percentage": "11.14%",
      "investMedium": "mediun 3",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT053",
      "fundHouse": "House Name 3",
      "investCategory": "category 2",
      "region": "Taiwan",
      "riskProfile": "risk4",
      "fundName": "[FOCUS FUND] House Name 3 : category 2 - TWD",
      "currency": "TWD",
      "threeMth": "+20.05",
      "sixMth": "+50.60",
      "oneYr": "-20.01",
      "threeYr": "+70.00",
      "threeYrsd": "+2.10",
      "percentage": "5.10%",
      "investMedium": "mediun 4",
      "isFocusFund": true,
      "focusFund": "FOCUS FUND",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT054",
      "fundHouse": "House Name 1",
      "investCategory": "category 1",
      "region": "Singapore",
      "riskProfile": "risk4",
      "fundName": "House Name 1 : category 2 - SGD",
      "currency": "SGD",
      "threeMth": "+3.05",
      "sixMth": "+4.60",
      "oneYr": "-1.31",
      "threeYr": "+3.00",
      "threeYrsd": "+6.90",
      "percentage": "10.14%",
      "investMedium": "mediun 2",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT055",
      "fundHouse": "House Name 2",
      "investCategory": "category 2",
      "region": "Singapore",
      "riskProfile": "risk4",
      "fundName": "House Name 2 : category 2 - SGD",
      "currency": "SGD",
      "threeMth": "+6.05",
      "sixMth": "+32.00",
      "oneYr": "-4.31",
      "threeYr": "+43.90",
      "threeYrsd": "+21.90",
      "percentage": "11.54%",
      "investMedium": "mediun 2",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT056",
      "fundHouse": "House Name 1",
      "investCategory": "category 1",
      "region": "Singapore",
      "riskProfile": "risk1",
      "fundName": "[FocusFund] House Name 1 : category 1 - SGD",
      "currency": "SGD",
      "threeMth": "+15.25",
      "sixMth": "+6.02",
      "oneYr": "-1.01",
      "threeYr": "+1.99",
      "threeYrsd": "+7.04",
      "percentage": "19.22%",
      "investMedium": "mediun 1",
      "isFocusFund": true,
      "focusFund": "FOCUS FUND",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT057",
      "fundHouse": "House Name 2",
      "investCategory": "category 2",
      "region": "Hong Kong",
      "riskProfile": "risk2",
      "fundName": "House Name 2 : category 2 - HKD",
      "currency": "HKD",
      "threeMth": "+12.75",
      "sixMth": "+3.02",
      "oneYr": "-2.01",
      "threeYr": "+18.99",
      "threeYrsd": "+10.24",
      "percentage": "5.34%",
      "investMedium": "mediun 1",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT058",
      "fundHouse": "House Name 2",
      "investCategory": "category 1",
      "region": "Hong Kong",
      "riskProfile": "risk3",
      "fundName": "[FOCUS FUND] House Name 2 : category 1 - HKD",
      "currency": "HKD",
      "threeMth": "+1.05",
      "sixMth": "+30.00",
      "oneYr": "-8.01",
      "threeYr": "+8.09",
      "threeYrsd": "+20.04",
      "percentage": "6.40%",
      "investMedium": "mediun 2",
      "isFocusFund": true,
      "focusFund": "FOCUS FUND",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT059",
      "fundHouse": "House Name 3",
      "investCategory": "category 2",
      "region": "Taiwan",
      "riskProfile": "risk4",
      "fundName": "House Name 3 : category 2 - TWD",
      "currency": "TWD",
      "threeMth": "+14.22",
      "sixMth": "+5.60",
      "oneYr": "-2.91",
      "threeYr": "+77.09",
      "threeYrsd": "+32.14",
      "percentage": "10.13%",
      "investMedium": "mediun 3",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT060",
      "fundHouse": "House Name 3",
      "investCategory": "category 2",
      "region": "Taiwan",
      "riskProfile": "risk4",
      "fundName": "[FOCUS FUND] House Name 3 : category 2 - TWD",
      "currency": "TWD",
      "threeMth": "+20.05",
      "sixMth": "+50.60",
      "oneYr": "-20.01",
      "threeYr": "+70.00",
      "threeYrsd": "+2.10",
      "percentage": "4.11%",
      "investMedium": "mediun 4",
      "isFocusFund": true,
      "focusFund": "FOCUS FUND",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT061",
      "fundHouse": "House Name 1",
      "investCategory": "category 1",
      "region": "Singapore",
      "riskProfile": "risk4",
      "fundName": "House Name 1 : category 2 - SGD",
      "currency": "SGD",
      "threeMth": "+3.05",
      "sixMth": "+4.60",
      "oneYr": "-1.31",
      "threeYr": "+3.00",
      "threeYrsd": "+6.90",
      "percentage": "11.14%",
      "investMedium": "mediun 2",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT062",
      "fundHouse": "House Name 2",
      "investCategory": "category 2",
      "region": "Singapore",
      "riskProfile": "risk4",
      "fundName": "House Name 2 : category 2 - SGD",
      "currency": "SGD",
      "threeMth": "+6.05",
      "sixMth": "+32.00",
      "oneYr": "-4.31",
      "threeYr": "+43.90",
      "threeYrsd": "+21.90",
      "percentage": "12.04%",
      "investMedium": "mediun 2",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT063",
      "fundHouse": "House Name 1",
      "investCategory": "category 1",
      "region": "Singapore",
      "riskProfile": "risk1",
      "fundName": "[FocusFund] House Name 1 : category 1 - SGD",
      "currency": "SGD",
      "threeMth": "+14.21",
      "sixMth": "+5.02",
      "oneYr": "-1.01",
      "threeYr": "+28.99",
      "threeYrsd": "+8.20",
      "percentage": "18.11%",
      "investMedium": "mediun 1",
      "isFocusFund": true,
      "focusFund": "FOCUS FUND",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT064",
      "fundHouse": "House Name 2",
      "investCategory": "category 2",
      "region": "Hong Kong",
      "riskProfile": "risk2",
      "fundName": "House Name 2 : category 2 - HKD",
      "currency": "HKD",
      "threeMth": "+12.75",
      "sixMth": "+3.02",
      "oneYr": "-2.01",
      "threeYr": "+18.99",
      "threeYrsd": "+10.24",
      "percentage": "4.02%",
      "investMedium": "mediun 1",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT065",
      "fundHouse": "House Name 2",
      "investCategory": "category 1",
      "region": "Hong Kong",
      "riskProfile": "risk3",
      "fundName": "[FOCUS FUND] House Name 2 : category 1 - HKD",
      "currency": "HKD",
      "threeMth": "+1.05",
      "sixMth": "+30.00",
      "oneYr": "-8.01",
      "threeYr": "+8.09",
      "threeYrsd": "+20.04",
      "percentage": "5.35%",
      "investMedium": "mediun 2",
      "isFocusFund": true,
      "focusFund": "FOCUS FUND",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT066",
      "fundHouse": "House Name 3",
      "investCategory": "category 2",
      "region": "Taiwan",
      "riskProfile": "risk4",
      "fundName": "House Name 3 : category 2 - TWD",
      "currency": "TWD",
      "threeMth": "+13.05",
      "sixMth": "+5.60",
      "oneYr": "-2.91",
      "threeYr": "+77.09",
      "threeYrsd": "+32.14",
      "percentage": "9.10%",
      "investMedium": "mediun 3",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT067",
      "fundHouse": "House Name 3",
      "investCategory": "category 2",
      "region": "Taiwan",
      "riskProfile": "risk4",
      "fundName": "[FOCUS FUND] House Name 3 : category 2 - TWD",
      "currency": "TWD",
      "threeMth": "+20.05",
      "sixMth": "+50.60",
      "oneYr": "-20.01",
      "threeYr": "+70.00",
      "threeYrsd": "+2.10",
      "percentage": "3.12%",
      "investMedium": "mediun 4",
      "isFocusFund": true,
      "focusFund": "FOCUS FUND",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT068",
      "fundHouse": "House Name 1",
      "investCategory": "category 1",
      "region": "Singapore",
      "riskProfile": "risk4",
      "fundName": "House Name 1 : category 2 - SGD",
      "currency": "SGD",
      "threeMth": "+3.05",
      "sixMth": "+4.60",
      "oneYr": "-1.31",
      "threeYr": "+3.00",
      "threeYrsd": "+6.90",
      "percentage": "12.14%",
      "investMedium": "mediun 2",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    },
    {
      "pid": "UT069",
      "fundHouse": "House Name 2",
      "investCategory": "category 2",
      "region": "Singapore",
      "riskProfile": "risk4",
      "fundName": "House Name 2 : category 2 - SGD",
      "currency": "SGD",
      "threeMth": "+6.05",
      "sixMth": "+32.00",
      "oneYr": "-4.31",
      "threeYr": "+43.90",
      "threeYrsd": "+21.90",
      "percentage": "13.50%",
      "investMedium": "mediun 2",
      "isFocusFund": false,
      "focusFund": "",
      "fundDetailUrl": "js/fundDetails.json"
    }
  ]
};